sudo: required
services:
  - docker

before_install:
  - docker build -t dmitryzinchenko/docker-react -f Dockerfile.dev .

script:
  - docker run dmitryzinchenko/docker-react npm run test -- --coverage
